<template>
  <view class="premium-arena">
    <view class="arena-content">
      <!-- High-End Background Decoration -->
      <view class="arena-bg">
        <view class="arena-orbit" />
        <view class="arena-glow" :class="{ flipping: isFlipping }" />
      </view>

      <!-- Holo Pedestal Base - Generated by Gemini Banana -->
      <image src="@/static/holo_pedestal.png" class="holo-pedestal" :alt="t('pedestalDecoration')" />

      <!-- 3D Coin -->
      <view class="coin-wrapper">
        <ThreeDCoin :result="displayOutcome" :flipping="isFlipping" />
      </view>

      <!-- Status Text -->
      <view class="status-box">
        <view class="game-status-pill">
          <view class="status-dot" :class="{ flipping: isFlipping }" />
          <text>{{ statusText }}</text>
        </view>
      </view>

      <!-- Results Indicator -->
      <view v-if="result && !isFlipping" class="result-banner" :class="{ won: result.won }" aria-live="polite">
        <text class="result-text">{{ result.won ? t("youWon") : t("youLost") }}</text>
        <text class="outcome-tag">{{ t(result.outcome) }}</text>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed } from "vue";
import ThreeDCoin from "@/components/ThreeDCoin.vue";

export interface GameResult {
  won: boolean;
  outcome: string;
}

const props = defineProps<{
  displayOutcome: "heads" | "tails" | null;
  isFlipping: boolean;
  result: GameResult | null;
}>();

const statusText = computed(() => {
  if (props.isFlipping) return t("flipping");
  if (props.result) return props.result.won ? t("youWon") : t("youLost");
  return t("placeBet");
});
</script>

<style lang="scss" scoped>
.premium-arena {
  width: 100%;
  padding: 40px 20px;
  position: relative;
  background: var(--coin-arena-bg);
  border-radius: 32px;
  border: 1px solid var(--coin-arena-border);
  overflow: hidden;
  backdrop-filter: blur(20px);
}

.arena-content {
  position: relative;
  z-index: 10;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 380px;
}

.arena-bg {
  position: absolute;
  inset: 0;
  z-index: -1;
}

.arena-orbit {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 250px;
  height: 250px;
  border: 1px dashed var(--coin-orbit-border);
  border-radius: 50%;
  transform: translate(-50%, -50%);
  animation: rotate 60s linear infinite;
}

.arena-glow {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 150px;
  height: 150px;
  background: radial-gradient(circle, rgba(0, 229, 153, 0.15) 0%, transparent 70%);
  transform: translate(-50%, -50%);
  transition: all 0.5s ease;

  &.flipping {
    background: radial-gradient(circle, rgba(251, 191, 36, 0.2) 0%, transparent 80%);
    width: 200px;
    height: 200px;
  }
}

.status-box {
  margin-top: 20px;
}

.result-banner {
  position: absolute;
  top: 20px;
  right: -50px;
  background: var(--coin-loss);
  padding: 8px 60px;
  transform: rotate(45deg);
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.3);
  display: flex;
  flex-direction: column;
  align-items: center;

  &.won {
    background: var(--coin-win);
  }
}

.result-text {
  font-size: 10px;
  font-weight: 900;
  letter-spacing: 2px;
  color: var(--coin-white);
}

.outcome-tag {
  font-size: 8px;
  font-weight: 700;
  opacity: 0.8;
  color: var(--coin-white);
}

@keyframes rotate {
  from {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  to {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
</style>
