module.exports = {
  preset: "jest-expo",
  testEnvironment: "node",
  testMatch: ["**/__tests__/**/*.test.ts?(x)"],
  collectCoverageFrom: [
    "src/lib/tokens.ts",
    "src/lib/neo/rpc.ts",
    "src/lib/api/transactions.ts",
    "src/lib/dapp/favorites.ts",
    "src/lib/dapp/injected.ts",
    "src/lib/accounts.ts",
    "src/lib/notifications.ts",
    "src/lib/i18n/index.ts",
    "src/lib/i18n/translate.ts",
    "src/lib/addressbook.ts",
    "src/lib/walletconnect.ts",
    "src/lib/qrcode.ts",
    "src/lib/nft.ts",
    "src/lib/staking.ts",
    "src/lib/gasfee.ts",
    "src/lib/backup.ts",
    "src/lib/signing.ts",
    "src/lib/prices.ts",
    "src/lib/security.ts",
    "src/lib/export.ts",
    "src/lib/notifcenter.ts",
    "!**/*.d.ts",
    "!**/node_modules/**",
  ],
  coverageThreshold: {
    "src/lib/tokens.ts": {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@noble/curves/nist$": "<rootDir>/node_modules/@noble/curves/nist.js",
    "^@noble/hashes/sha2$": "<rootDir>/node_modules/@noble/hashes/sha2.js",
    "^@noble/hashes/legacy$": "<rootDir>/node_modules/@noble/hashes/legacy.js",
    "^@noble/hashes/utils$": "<rootDir>/node_modules/@noble/hashes/utils.js",
  },
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  transformIgnorePatterns: [
    "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@noble/.*|\\.pnpm)",
  ],
};
