packages:
  - "packages/**"
  - "platform/*"
  - "miniapps/*"
  - "miniapps/shared"

catalogs:
  default:
    "@cityofzion/neon-core": ^5.8.0
    "@dcloudio/uni-app": 3.0.0-4060620250520001
    "@dcloudio/uni-cli-shared": 3.0.0-4060620250520001
    "@dcloudio/uni-components": 3.0.0-4060620250520001
    "@dcloudio/uni-h5": 3.0.0-4060620250520001
    "@dcloudio/vite-plugin-uni": 3.0.0-4060620250520001
    "@noble/curves": ^2.0.1
    "@noble/hashes": ^2.0.1
    sass: ^1.77.0
    terser: ^5.46.0
    typescript: ^5.4.5
    vite: ^5.2.8
    vue: ^3.5.0
