# Development environment configuration
replicaCount: 1

image:
  tag: dev

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false

ingress:
  enabled: false

config:
  environment: development
  logging:
    level: debug
  database:
    host: postgresql.development.svc.cluster.local
  tee:
    memory_limit: 128
    timeout_sec: 5

persistence:
  enabled: true
  size: 1Gi
  storageClass: standard

postgresql:
  auth:
    username: postgres
    password: postgres
    database: service_layer
  primary:
    persistence:
      size: 1Gi

prometheus:
  enabled: true
  server:
    persistentVolume:
      size: 1Gi
  alertmanager:
    enabled: false
  nodeExporter:
    enabled: false

grafana:
  enabled: true
  adminPassword: admin
  persistence:
    enabled: true
    size: 1Gi 