# Production environment configuration
replicaCount: 3

image:
  tag: latest

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 1Gi

autoscaling:
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

ingress:
  hosts:
    - host: api.service-layer.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: service-layer-tls
      hosts:
        - api.service-layer.io

config:
  environment: production
  logging:
    level: info
  database:
    max_open_conns: 50
    max_idle_conns: 25
    conn_max_lifetime: 300
  tee:
    memory_limit: 256
    timeout_sec: 10

persistence:
  size: 20Gi
  storageClass: premium

postgresql:
  primary:
    persistence:
      size: 20Gi
      storageClass: premium
  replication:
    enabled: true
    readReplicas: 2
  metrics:
    enabled: true

prometheus:
  server:
    persistentVolume:
      size: 50Gi
      storageClass: premium
  alertmanager:
    persistence:
      enabled: true
      size: 10Gi

grafana:
  persistence:
    size: 10Gi
    storageClass: premium
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 256Mi 