# Staging environment configuration
replicaCount: 2

image:
  tag: staging

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 512Mi

autoscaling:
  minReplicas: 2
  maxReplicas: 5

ingress:
  hosts:
    - host: staging-api.service-layer.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: staging-service-layer-tls
      hosts:
        - staging-api.service-layer.io

config:
  environment: staging
  logging:
    level: debug

postgresql:
  primary:
    persistence:
      size: 5Gi

prometheus:
  server:
    persistentVolume:
      size: 5Gi

grafana:
  persistence:
    size: 2Gi 