#!/bin/bash
# Generate complete uni-app project structure for all MiniApps

APPS_DIR="/home/neo/git/service_layer/miniapps-uniapp/apps"
SHARED_DIR="/home/neo/git/service_layer/miniapps-uniapp/shared"

# App metadata: app-name|title|category|description
declare -a APPS=(
  "lottery|Neo Lottery|gaming|Provably fair lottery draws"
  "coin-flip|Coin Flip|gaming|Simple 50/50 betting game"
  "dice-game|Dice Game|gaming|Roll dice and win prizes"
  "scratch-card|Scratch Card|gaming|Instant win scratch cards"
  "secret-poker|Secret Poker|gaming|Private poker with hidden cards"
  "neo-crash|Neo Crash|gaming|Multiplier crash game"
  "candle-wars|Candle Wars|gaming|Predict price movements"
  "algo-battle|Algo Battle|gaming|Algorithm trading competition"
  "fog-chess|Fog Chess|gaming|Chess with fog of war"
  "fog-puzzle|Fog Puzzle|gaming|Hidden puzzle solving"
  "crypto-riddle|Crypto Riddle|gaming|Solve riddles for rewards"
  "world-piano|World Piano|gaming|Collaborative music creation"
  "million-piece-map|Million Piece Map|gaming|Collaborative pixel art"
  "puzzle-mining|Puzzle Mining|gaming|Mine by solving puzzles"
  "scream-to-earn|Scream to Earn|gaming|Voice-powered earnings"
  "flashloan|Flash Loan|defi|Instant uncollateralized loans"
  "ai-trader|AI Trader|defi|AI-powered trading signals"
  "grid-bot|Grid Bot|defi|Automated grid trading"
  "bridge-guardian|Bridge Guardian|defi|Cross-chain bridge monitor"
  "gas-circle|Gas Circle|defi|GAS savings circles"
  "il-guard|IL Guard|defi|Impermanent loss protection"
  "compound-capsule|Compound Capsule|defi|Auto-compounding yields"
  "dark-pool|Dark Pool|defi|Private large trades"
  "dutch-auction|Dutch Auction|defi|Descending price auctions"
  "no-loss-lottery|No Loss Lottery|defi|Yield-based lottery"
  "quantum-swap|Quantum Swap|defi|MEV-resistant swaps"
  "self-loan|Self Loan|defi|Self-collateralized loans"
  "ai-soulmate|AI Soulmate|social|AI companion chat"
  "red-envelope|Red Envelope|social|Lucky money sharing"
  "dark-radio|Dark Radio|social|Anonymous broadcasts"
  "dev-tipping|Dev Tipping|social|Support developers"
  "bounty-hunter|Bounty Hunter|social|Bug bounty platform"
  "breakup-contract|Breakup Contract|social|Relationship agreements"
  "ex-files|Ex Files|social|Shared memories vault"
  "geo-spotlight|Geo Spotlight|social|Location-based content"
  "whisper-chain|Whisper Chain|social|Anonymous messaging"
  "canvas|Canvas|nft|Collaborative NFT art"
  "nft-evolve|NFT Evolve|nft|Evolving NFT traits"
  "nft-chimera|NFT Chimera|nft|Merge NFTs together"
  "schrodinger-nft|Schrodinger NFT|nft|Quantum state NFTs"
  "melting-asset|Melting Asset|nft|Time-decaying NFTs"
  "on-chain-tarot|On-Chain Tarot|nft|Blockchain tarot readings"
  "time-capsule|Time Capsule|nft|Future-locked content"
  "heritage-trust|Heritage Trust|nft|Digital inheritance"
  "garden-of-neo|Garden of Neo|nft|Virtual garden NFTs"
  "graveyard|Graveyard|nft|Memorial NFTs"
  "parasite|Parasite|nft|NFT that feeds on others"
  "pay-to-view|Pay to View|nft|Gated NFT content"
  "dead-switch|Dead Switch|nft|Dead man's switch"
  "secret-vote|Secret Vote|governance|Private voting"
  "gov-booster|Gov Booster|governance|Governance power boost"
  "prediction-market|Prediction Market|governance|Event prediction"
  "burn-league|Burn League|governance|Token burning competition"
  "doomsday-clock|Doomsday Clock|governance|Community countdown"
  "masquerade-dao|Masquerade DAO|governance|Anonymous governance"
  "gov-merc|Gov Merc|governance|Governance mercenaries"
  "price-ticker|Price Ticker|utility|Real-time prices"
  "guardian-policy|Guardian Policy|utility|Policy management"
  "unbreakable-vault|Unbreakable Vault|utility|Secure storage"
  "zk-badge|ZK Badge|utility|Zero-knowledge badges"
)

echo "Generating uni-app project structure for ${#APPS[@]} apps..."

for app_entry in "${APPS[@]}"; do
  IFS='|' read -r app_name title category description <<< "$app_entry"
  APP_DIR="$APPS_DIR/$app_name"

  if [ ! -d "$APP_DIR" ]; then
    echo "Skipping $app_name - directory not found"
    continue
  fi

  echo "Processing: $app_name ($category)"

  # Create directories
  mkdir -p "$APP_DIR/src/static"

  # Copy shared folder
  if [ ! -d "$APP_DIR/src/shared" ]; then
    cp -r "$SHARED_DIR" "$APP_DIR/src/shared"
  fi
done

echo "Directory structure created. Template files will be generated by Node.js script."
