#!/bin/bash
# Generate complete uni-app project structure for all MiniApps

APPS_DIR="/home/neo/git/service_layer/miniapps-uniapp/apps"
SHARED_DIR="/home/neo/git/service_layer/miniapps-uniapp/shared"

# App metadata: app-name|title|category|description
declare -a APPS=(
  "lottery|Neo Lottery|gaming|Provably fair lottery draws"
  "coin-flip|Coin Flip|gaming|Simple 50/50 betting game"
  "dice-game|Dice Game|gaming|Roll dice and win prizes"
  "scratch-card|Scratch Card|gaming|Instant win scratch cards"
  "secret-poker|Secret Poker|gaming|Private poker with hidden cards"
  "neo-crash|Neo Crash|gaming|Multiplier crash game"
  "fog-puzzle|Fog Puzzle|gaming|Hidden puzzle solving"
  "crypto-riddle|Crypto Riddle|gaming|Solve riddles for rewards"
  "million-piece-map|Million Piece Map|gaming|Collaborative pixel art"
  "puzzle-mining|Puzzle Mining|gaming|Mine by solving puzzles"
  "flashloan|Flash Loan|defi|Instant uncollateralized loans"
  "gas-circle|Gas Circle|defi|GAS savings circles"
  "compound-capsule|Compound Capsule|defi|Auto-compounding yields"
  "self-loan|Self Loan|defi|Self-collateralized loans"
  "red-envelope|Red Envelope|social|Lucky money sharing"
  "dev-tipping|Dev Tipping|social|Support developers"
  "breakup-contract|Breakup Contract|social|Relationship agreements"
  "ex-files|Ex Files|social|Shared memories vault"
  "canvas|Canvas|nft|Collaborative NFT art"
  "on-chain-tarot|On-Chain Tarot|nft|Blockchain tarot readings"
  "time-capsule|Time Capsule|nft|Future-locked content"
  "heritage-trust|Heritage Trust|nft|Digital inheritance"
  "garden-of-neo|Garden of Neo|nft|Virtual garden NFTs"
  "graveyard|Graveyard|nft|Memorial NFTs"
  "gov-booster|Gov Booster|governance|Governance power boost"
  "burn-league|Burn League|governance|Token burning competition"
  "doomsday-clock|Doomsday Clock|governance|Community countdown"
  "masquerade-dao|Masquerade DAO|governance|Anonymous governance"
  "gov-merc|Gov Merc|governance|Governance mercenaries"
  "guardian-policy|Guardian Policy|utility|Policy management"
  "unbreakable-vault|Unbreakable Vault|utility|Secure storage"
)

echo "Generating uni-app project structure for ${#APPS[@]} apps..."

for app_entry in "${APPS[@]}"; do
  IFS='|' read -r app_name title category description <<< "$app_entry"
  APP_DIR="$APPS_DIR/$app_name"

  if [ ! -d "$APP_DIR" ]; then
    echo "Skipping $app_name - directory not found"
    continue
  fi

  echo "Processing: $app_name ($category)"

  # Create directories
  mkdir -p "$APP_DIR/src/static"

  # Copy shared folder
  if [ ! -d "$APP_DIR/src/shared" ]; then
    cp -r "$SHARED_DIR" "$APP_DIR/src/shared"
  fi
done

echo "Directory structure created. Template files will be generated by Node.js script."
