<template>
  <view class="theme-coin-flip">
    <!-- Vault Decorations - Generated by Gemini CLI -->
    <view class="neon-accent-left" />
    <view class="neon-accent-right" />
    <view class="hex-decoration hex-1" />
    <view class="hex-decoration hex-2" />
    <view class="vignette-overlay" />

    <view class="data-stream" v-if="activeTab === 'game'">
      <view
        v-for="i in 10"
        :key="i"
        class="stream-line"
        :style="{
          left: i * 10 + '%',
          animationDuration: 2 + Math.random() * 3 + 's',
          animationDelay: Math.random() * 5 + 's',
        }"
      />
    </view>

    <ErrorBoundary @error="handleBoundaryError" @retry="resetGame" :fallback-message="t('gameErrorFallback')">
      <MiniAppTemplate
        :config="templateConfig"
        :state="appState"
        :t="t"
        :fireworks-active="showWinOverlay"
        @tab-change="activeTab = $event"
      >
        <!-- Desktop Sidebar -->
        <template #desktop-sidebar>
          <SidebarPanel :title="t('overview')" :items="sidebarItems" />
        </template>

        <!-- Game content -->
        <template #content>
          <!-- Wallet Connection Warning -->
          <view v-if="!address" class="wallet-warning">
            <NeoCard variant="warning" class="text-center">
              <text class="font-bold">{{ t("connectWalletToPlay") }}</text>
              <NeoButton variant="primary" size="sm" class="mt-2" @click="connectWallet">
                {{ t("connectWallet") }}
              </NeoButton>
            </NeoCard>
          </view>

          <!-- Coin Arena -->
          <view class="arena-container">
            <CoinArena
              :display-outcome="displayOutcome"
              :is-flipping="isFlipping"
              :result="result"
              :t="t as (key: string) => string"
            />
          </view>

          <!-- Bet Controls -->
          <view class="controls-container">
            <BetControls
              v-model:choice="choice"
              v-model:betAmount="betAmount"
              :is-flipping="isFlipping"
              :can-bet="canBet"
              :validation-error="validationError"
              :t="t as (key: string) => string"
              @flip="handleFlip"
            />
          </view>

          <!-- Error Message Overlay -->
          <view v-if="errorMessage" class="error-toast" :class="{ 'error-retryable': canRetryError }">
            <text>{{ errorMessage }}</text>
            <view v-if="canRetryError" class="retry-actions">
              <NeoButton variant="secondary" size="sm" @click="retryOperation">
                {{ t("retry") }}
              </NeoButton>
            </view>
          </view>

          <!-- Result Modal -->
          <ResultOverlay
            :visible="showWinOverlay"
            :win-amount="winAmount"
            :t="t as (key: string) => string"
            @close="showWinOverlay = false"
          />
        </template>

        <!-- Stats tab -->
        <template #tab-stats>
          <NeoCard variant="erobo" class="mb-6">
            <NeoStats :stats="gameStats" />
          </NeoCard>
        </template>
      </MiniAppTemplate>
    </ErrorBoundary>
  </view>
</template>

<script setup lang="ts">
import "../../static/coin-flip.css";
import { ref, computed } from "vue";
import { useWallet } from "@neo/uniapp-sdk";
import type { WalletSDK } from "@neo/types";
import { useI18n } from "@/composables/useI18n";
import { MiniAppTemplate, NeoCard, NeoStats, NeoButton, SidebarPanel, type StatItem, ErrorBoundary } from "@shared/components";
import type { MiniAppTemplateConfig } from "@shared/types/template-config";
import CoinArena from "./components/CoinArena.vue";
import BetControls from "./components/BetControls.vue";
import ResultOverlay from "./components/ResultOverlay.vue";
import { useCoinFlipGame } from "./composables/useCoinFlipGame";

const { t } = useI18n();
const wallet = useWallet() as WalletSDK;
const { address } = wallet;

const {
  betAmount, choice, totalWon, isFlipping, result, displayOutcome,
  showWinOverlay, winAmount, errorMessage, validationError, canRetryError,
  canBet, wins, losses, totalGames, formatNum,
  connectWallet, resetGame, handleBoundaryError, retryOperation, handleFlip,
} = useCoinFlipGame(wallet, t);

const templateConfig: MiniAppTemplateConfig = {
  contentType: "game-board",
  tabs: [
    { key: "game", labelKey: "game", icon: "\uD83C\uDFAE", default: true },
    { key: "stats", labelKey: "stats", icon: "\uD83D\uDCCA" },
    { key: "docs", labelKey: "docs", icon: "\uD83D\uDCD6" },
  ],
  features: {
    fireworks: true,
    chainWarning: true,
    statusMessages: true,
    docs: {
      titleKey: "title",
      subtitleKey: "docSubtitle",
      stepKeys: ["step1", "step2", "step3", "step4"],
      featureKeys: [
        { nameKey: "feature1Name", descKey: "feature1Desc" },
        { nameKey: "feature2Name", descKey: "feature2Desc" },
      ],
    },
  },
};

const activeTab = ref("game");

const gameStats = computed<StatItem[]>(() => [
  { label: t("totalGames"), value: wins.value + losses.value },
  { label: t("wins"), value: wins.value, variant: "success" },
  { label: t("losses"), value: losses.value, variant: "danger" },
  { label: t("totalWon"), value: `${formatNum(totalWon.value)} GAS`, variant: "accent" },
]);

const sidebarItems = computed(() => [
  { label: t("totalGames"), value: totalGames.value },
  { label: t("wins"), value: wins.value },
  { label: t("losses"), value: losses.value },
  { label: t("totalWon"), value: `${formatNum(totalWon.value)} GAS` },
]);

const appState = computed(() => ({
  totalGames: wins.value + losses.value,
  wins: wins.value,
  losses: losses.value,
  totalWon: totalWon.value,
}));
</script>

<style lang="scss" scoped>
@use "@shared/styles/tokens.scss" as *;
@use "@shared/styles/variables.scss" as *;
@import "./coin-flip-theme.scss";

:global(page) {
  background: var(--coin-bg-primary);
}

.tab-content {
  padding: 20px;
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 24px;
  background: var(--bg-primary);
  color: var(--text-primary);
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  position: relative;
  z-index: 1;
}

.arena-container {
  width: 100%;
  margin-top: 10px;
}

.controls-container {
  width: 100%;
}

.wallet-warning {
  margin-bottom: 16px;
}

.error-toast {
  position: fixed;
  top: 100px;
  left: 50%;
  transform: translateX(-50%);
  background: var(--coin-error-bg);
  color: var(--coin-error-text);
  padding: 12px 24px;
  border-radius: 99px;
  font-weight: 700;
  font-size: 14px;
  backdrop-filter: blur(10px);
  z-index: 3000;
  box-shadow: var(--coin-error-shadow);
  animation: toast-in 0.3s ease-out;
  max-width: 90%;
  text-align: center;
}

.error-toast.error-retryable {
  padding-bottom: 48px;
}

.retry-actions {
  position: absolute;
  bottom: 8px;
  left: 50%;
  transform: translateX(-50%);
}

@keyframes toast-in {
  from {
    transform: translate(-50%, -20px);
    opacity: 0;
  }
  to {
    transform: translate(-50%, 0);
    opacity: 1;
  }
}

:deep(.neo-stats) {
  .stat-card {
    background: var(--coin-stat-bg);
    border: 1px solid var(--coin-stat-border);
  }
  .stat-value {
    font-weight: 900;
    letter-spacing: -1px;
  }
}
</style>
