<script setup lang="ts">
import { computed } from "vue";

const props = defineProps<{
  result: "heads" | "tails" | null;
  flipping: boolean;
}>();

const coinStyle = computed(() => {
  if (props.flipping) {
    return {
      animation: 'coin-spin-infinite 0.5s linear infinite',
    };
  }

  // Resting state
  // We want to land on the correct face.
  // To avoid snapping, we could calculate the closest multiple of 360 + result offset,
  // but for simplicity, standard transition to 0 or 180 works if we accept a bit of "rewind" or "fast forward".
  // A better way is to disable animation and just set the transform, 
  // but let's try a smooth transition to a fixed angle.
  const rotation = props.result === "tails" ? 180 : 0;
  
  // To make it look like it's "landing" from the spin:
  // We ideally want to stop the infinite spin and transition to this.
  // Implementation note: CSS animation to transition is tricky. 
  // We'll trust the browser to interpolate from the computed style state or just snap to a "landing" animation.
  
  return {
    transform: `rotateY(${rotation}deg) rotateX(0deg)`,
    transition: "transform 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275)",
  };
});
</script>

<template>
  <view class="coin-scene">
    <view class="coin-container" :class="{ flipping: flipping }" :style="coinStyle">
      <!-- Front Face (Heads / NEO) - Generated by Gemini Banana -->
      <view class="coin-face front">
        <image src="@/static/coin_heads.png" class="coin-img" alt="" />
      </view>

      <!-- Back Face (Tails / GAS) - Generated by Gemini Banana -->
      <view class="coin-face back">
        <image src="@/static/coin_tails.png" class="coin-img" alt="" />
      </view>
    </view>
    
    <!-- Floor Shadow -->
    <view class="coin-shadow" :class="{ 'is-flipping': flipping }" />
  </view>
</template>

<style scoped lang="scss">
.coin-scene {
  position: relative;
  width: 200px; /* Increased size for high-res assets */
  height: 200px;
  perspective: 1200px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.coin-container {
  width: 180px;
  height: 180px;
  position: relative;
  transform-style: preserve-3d;
  transition: transform 0.6s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.coin-face {
  position: absolute;
  inset: 0;
  border-radius: 50%;
  backface-visibility: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
}

.coin-img {
  width: 100%;
  height: 100%;
  border-radius: 50%;
  backface-visibility: hidden; /* Ensure image backface is hidden */
}

/* Adjust Z-index and transforms to prevent z-fighting */
.front {
  z-index: 2;
  transform: translateZ(1px); /* Small offset */
}

.back {
  transform: rotateY(180deg) translateZ(1px);
}

.coin-shadow {
  position: absolute;
  bottom: -40px;
  left: 50%;
  transform: translateX(-50%) rotateX(75deg);
  width: 140px;
  height: 140px;
  background: radial-gradient(circle, rgba(0,0,0,0.6) 0%, transparent 70%);
  border-radius: 50%;
  transition: all 0.3s ease;
  z-index: -1;
}

.is-flipping {
  animation: shadow-flip 2.5s infinite;
}

@keyframes shadow-flip {
  0%, 100% { transform: translateX(-50%) rotateX(75deg) scale(1); opacity: 0.5; }
  20% { transform: translateX(-50%) rotateX(75deg) scale(1.5); opacity: 0.2; }
  50% { transform: translateX(-50%) rotateX(75deg) scale(0.7); opacity: 0.15; }
  80% { transform: translateX(-50%) rotateX(75deg) scale(1.2); opacity: 0.3; }
}

@keyframes coin-bounce {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-8px); }
}

@keyframes coin-spin-infinite {
  0% { transform: rotateY(0deg); }
  100% { transform: rotateY(360deg); }
}

.coin-container:not(.flipping) {
  animation: coin-bounce 3s infinite ease-in-out;
}
</style>
