global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Alertmanager could be added here in the future

rule_files:
  # Rules could be added here in the future

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'service_layer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8080']