apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-layer.configMapName" . }}
  labels:
    helm.sh/chart: {{ include "service-layer.chart" . }}
    app.kubernetes.io/name: {{ include "service-layer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |
    environment: {{ .Values.config.environment }}
    server:
      port: {{ .Values.config.server.port }}
      read_timeout: {{ .Values.config.server.read_timeout }}
      write_timeout: {{ .Values.config.server.write_timeout }}
      idle_timeout: {{ .Values.config.server.idle_timeout }}
      max_header_bytes: {{ .Values.config.server.max_header_bytes }}
    database:
      host: {{ .Values.config.database.host }}
      port: {{ .Values.config.database.port }}
      user: {{ .Values.config.database.user }}
      name: {{ .Values.config.database.name }}
      ssl_mode: {{ .Values.config.database.ssl_mode }}
      max_open_conns: {{ .Values.config.database.max_open_conns }}
      max_idle_conns: {{ .Values.config.database.max_idle_conns }}
      conn_max_lifetime: {{ .Values.config.database.conn_max_lifetime }}
    auth:
      jwt_secret: ${AUTH_JWT_SECRET}
      token_expiry: {{ .Values.config.auth.token_expiry }}
      refresh_token_expiry: {{ .Values.config.auth.refresh_token_expiry }}
    neo:
      urls:
      {{- range .Values.config.neo.urls }}
        - {{ . }}
      {{- end }}
      wallet_path: {{ .Values.config.neo.wallet_path }}
    tee:
      provider: {{ .Values.config.tee.provider }}
      memory_limit: {{ .Values.config.tee.memory_limit }}
      timeout_sec: {{ .Values.config.tee.timeout_sec }}
      attestation:
        url: {{ .Values.config.tee.attestation.url }}
        policy: {{ .Values.config.tee.attestation.policy }}
    security:
      encryption_key: ${SECURITY_ENCRYPTION_KEY}
      secrets_ttl: {{ .Values.config.security.secrets_ttl }}
    logging:
      level: {{ .Values.config.logging.level }}
      format: {{ .Values.config.logging.format }}
      output: {{ .Values.config.logging.output }} 