apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-layer.secretsName" . }}
  labels:
    helm.sh/chart: {{ include "service-layer.chart" . }}
    app.kubernetes.io/name: {{ include "service-layer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  db-password: {{ .Values.secrets.db_password | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwt_secret | b64enc | quote }}
  encryption-key: {{ .Values.secrets.encryption_key | b64enc | quote }} 