global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load and evaluate rules
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Service Layer metrics
  - job_name: 'service_layer'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['service_layer:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']