[build]
  base = "website"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify caching configuration
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Ensure we preserve the Next.js cache directory between builds
[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
    paths = [".next/cache"]